import = [
    "~/.config/alacritty/themes/themes/taerminal.toml"
]

[env]
TERM="xterm-256color"
COLORTERM="truecolor"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"

[font]
# Fonts From:
# https://www.nerdfonts.com/font-downloads
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLSG Nerd Font Mono", style = "Bold Italic" }
size = 10


[cursor]
style = { shape = "Block", blinking = "On" }

[colors.primary]
background = "#0a0021"
foreground = "#b1fcd5"