[colors]
background = #000000
foreground = #FFFFFF
separator = #777777

[bar/main]
width = 100%
height = 30
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = MesloLGS Nerd Font:style=Regular:pixelsize=12;2

tray-position = right
tray-padding = 2
tray-maxsize = 16

module-margin = 1

separator = |
separator-foreground = ${colors.separator}

modules-left = workspaces
modules-center = date
modules-right = volume wlan battery


; ---------------- Modules ----------------

[module/workspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.foreground}
label-active-foreground = ${colors.background}
label-active-padding = 2
label-occupied = %name%
label-occupied-padding = 2
label-empty = %name%
label-empty-foreground = #555555
label-empty-padding = 2

[module/date]
type = internal/date
interval = 1
date = %a, %d %b %Y
time = %I:%M %p
format = <label>
label = %date%  %time%

[module/volume]
type = internal/pulseaudio
format-volume = <label-volume>
format-muted  = <label-muted>
label-volume =   %percentage%%
label-muted  =   muted

[module/wlan]
type = internal/network
interface = wlo1
interval = 3
format-connected    = <label-connected>
format-disconnected = <label-disconnected>
label-connected     =   %essid%
label-disconnected  = 睊

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
format-charging    = <label-charging>
format-discharging = <label-discharging>
format-full        = <label-full>
format-low         = <label-low>
label-charging     =   %percentage%%
label-discharging  =   %percentage%%
label-full         =   %percentage%%
label-low          =   %percentage%%